# permissions for end users to edit diningrooms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: explore-k8s-custom-controllers
    app.kubernetes.io/managed-by: kustomize
  name: diningroom-editor-role
rules:
- apiGroups:
  - smarthome.danielguo
  resources:
  - diningrooms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - smarthome.danielguo
  resources:
  - diningrooms/status
  verbs:
  - get
