# permissions for end users to view diningrooms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: explore-k8s-custom-controllers
    app.kubernetes.io/managed-by: kustomize
  name: diningroom-viewer-role
rules:
- apiGroups:
  - smarthome.danielguo
  resources:
  - diningrooms
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - smarthome.danielguo
  resources:
  - diningrooms/status
  verbs:
  - get
