apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: explore-k8s-custom-controllers
    app.kubernetes.io/managed-by: kustomize
  name: controller-manager
  namespace: system
